// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const intro: string;
export const fadeUp: string;
export const button: string;
export const buttonDown: string;
export const buttonBefore: string;
export const buttonAfter: string;
