// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const toggleButton: string;
export const active: string;
export const nav: string;
export const currentLink: string;
export const mobileMenu: string;
