// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const toggleButton: string;
export const active: string;
export const nav: string;
export const headerTransparent: string;
export const darkHeader: string;
export const logo: string;
export const fadeDown: string;
export const contactButton: string;
export const currentLink: string;
export const fadeIn: string;
export const mobileMenu: string;
export const menuOpen: string;
